[workspace.package]
[package]
name = "rsp-client-linea"
description = ""
edition = "2021"

[dependencies]
bincode = "1.3.3"

# workspace
rsp-client-executor = { path = "../../crates/executor/client" }

# sp1
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1-wip", branch = "yuwen/mhz-profiling" }

# Statically turns off logging
log = { version = "0.4", features = ["max_level_off", "release_max_level_off"] }
tracing = { version = "0.1", features = ["max_level_off", "release_max_level_off"] }

[patch.crates-io]
# Precompile patches
sha2 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", tag = "patch-sha2-0.10.8-sp1-4.0.0", package = "sha2" }
ecdsa-core = { git = "https://github.com/sp1-patches/signatures", tag = "patch-0.16.9-sp1-4.0.0", package = "ecdsa" }
bn = { git = "https://github.com/sp1-patches/bn", tag = "patch-0.6.0-sp1-4.0.0", package = "substrate-bn" }
sha3 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", tag = "patch-sha3-0.10.8-sp1-4.0.0" }
